apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: ziadalbana/central-station:2.0
          imagePullPolicy: IfNotPresent
          env:
            # Add any environment variables required by your Kafka consumer
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "station"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:StartFlightRecording:filename=myrecording.jfr,duration=60s"
          # Add any other configuration specific to your Kafka consumer container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
        - name: writer-container
          image: ziadalbana/central-station:3.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-directory
          env:
            # Add any environment variables required by your Kafka consumer
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "station"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:StartFlightRecording:filename=myrecording.jfr,duration=60s"
        - name: elastic-search
          image: ziadalbana/elastic-search:1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-directory
      volumes:
        - name: shared-volume
          emptyDir: {}

